export const companyThemes = {
  companyA: {
    primary: "#1E3955",
    secondary: "#00467B",
    background: "white",
    componentBackground: "#a6b8ea26",
    text: "black",
    border: "#475467",
    tilesColor: "white",
    fontFamily: "Nunito Sans, sans-serif",
  },
  companyB: {
    primary: "#E1891F",
    secondary: "#FFA83F",
    background: "#475467",
    componentBackground: "##b5b9c461",
    text: "#EEF2F6",
    tilesColor: "#b5b9c461",
    border: "#EEF2F6",
    fontFamily: "Roboto, sans-serif",
  },
  companyC: {
    primary: "#4657BC",
    secondary: "#EEF2F6",
    background: "#CBD0DD",
    componentBackground: "#b5b9c461",
    border: "#475467",
    tilesColor: "#b5b9c461",
    text: "#475467",
    fontFamily: "Poppins, sans-serif",
  },
};
