export enum ApiActions {
  SIGN_IN = "SIGN_IN",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  GET_JOBS = "GET_JOBS",
  GET_JOB_DETAILS = "GET_JOB_DETAILS",
  GET_COMPANIES = "GET_COMPANIES",
  GET_COMPANY_DETAILS = "GET_COMPANY_DETAILS",
  GET_APPOINTMENTS = "GET_APPOINTMENTS",
  GET_USERS = "GET_USERS",
  GET_LOCATIONS = "GET_LOCATIONS",
  GET_INVENTORIES = "GET_INVENTORIES",
}
