export const appRoute = {
  default: "/",
  book: "/book",
  job: "/jobs",
};

export const protectedRoutes = [""];
export const unProtectedRoutes = [appRoute.default, appRoute.book];

export const imagesPath = {
  loginSideImage: "/backgrounds/flood-login-img.svg",
  lock: "/images/lock.svg",
  logo: "/images/logo.svg",
  hero: "/images/hero.svg",
  home: "icons/home.svg",
  atmosphere: "/icons/droplet.svg",
  arrow: "/images/arrow-down.svg",
  darkNLights: "/icons/dark-toggle.svg",
  avatar: "/icons/icons=avaters.svg",
  folder: "/icons/folder.svg",
  send: "/icons/send.svg",
  dollar: "/icons/dollar-sign.svg",
  bookOpen: "/icons/book-open.svg",
  userCheck: "/icons/user-check.svg",
  users: "/icons/users.svg",
  textFile: "/icons/file-text.svg",
  cpu: "/icons/cpu.svg",
  box: "icons/box.svg",
  material: "/icons/database.svg",
  award: "/icons/award.svg",
  octagon: "/icons/octagon.svg",
  truck: "icons/truck.svg",
  appointment: "/icons/message-square.svg",
  calender: "/icons/calendar.svg",
  briefcase: "/icons/briefcase.svg",
  location: "/icons/map-pin.svg",
  disc: "/icons/disc.svg",
  exhaustloader: "/icons/loader.svg",
  menuToggle: "/icons/menu-toggle.svg",
  download: "/images/download.svg",
  downloadWhite: "/images/download-white.svg",
  delete: "/images/delete.svg",
  info: "/images/info.svg",
  add: "/images/add.svg",
  search: "/images/search.svg",
  placeholder: "/images/placeholder.svg",
  worldPay: "/images/footer-icon/worldpay.svg",
  masterIcon: "/images/footer-icon/master.svg",
  email: "/images/footer-icon/email.svg",
  phone: "/images/footer-icon/phone.svg",
  map: "/images/footer-icon/map.svg",
  check: "/images/check.svg",
  uploadDocument: "/images/upload-document.svg",
  generalDetails: "/images/general-details.svg",
  checkPrimary: "/images/check-primary.svg",
  checkSecondary: "/images/check-secondary.svg",
  checkSuccess: "/images/check-success.svg",
  generatedRebuttal: "/images/generated-rebuttal.svg",
  archive: "/icons/archive.svg",
  secure: "/images/secure.svg",
  view: "/images/view.svg",
  file: "/images/file.svg",
  paymentRequired: "/images/payment-required.svg",
  paymentSuccess: "/images/payment-success.svg",
  nextArrow: "/images/next-arrow.svg",
  heroBackground: "/images/Layer_1.svg",
  closeIcon: "/images/close.svg",
  alertIcon: "/icons/bell.svg",
  framer: "icons/framer.svg",
  cloudRainIcon: "/icons/cloud-rain.svg",
  positionIcon: "/icons/position.svg",
  plusIcon: "/images/blue-plus.svg",
  totalJobs: "/icons/collection-icons/totalJobs.svg",
  totalBills: "/icons/collection-icons/totalBills.svg",
  totalCollected: "/icons/collection-icons/totalCollected.svg",
  totalOutstanding: "/icons/collection-icons/totalOutstanding.svg",
  colorPlate: "/icons/color-plate.svg",
  imageUploader: "/icons/Image-Icon.svg",
  equipmentIcon: "/icons/eq-icons.svg",
  userLocation: "icons/user-icons/userPrimaryLocation.svg",
  user: "/icons/user-icons/user.svg",
  userBuilding: "/icons/user-icons/userBuilding.svg",
  userAlert: "/icons/user-icons/userAlert.svg",
  userGroup: "/icons/user-icons/userGroup.svg",
};

export const MAX_FILE_SIZE = 5 * 1024 * 1024;
export const TEXT_COPIED = "Text copied";
export enum GeneralEnums {
  SUCCESS = "success",
  UPLOADING = "uploading",
  IDLE = "idle",
  BLANK = "_blank",
}

export const rooms = [
  "Attic",
  "Loft",
  "Spare Room",
  "Bedroom",
  "Bathroom",
  "Balcony",
  "Nursery",
  "Study",
  "Utility Room",
  "Conservatory",
  "Living Room",
  "Dining Room",
  "Kitchen",
  "Garage",
  "Mud Room",
  "Basement",
  "Wine Cellar",
  "Hallway",
  "Library",
  "Closet",
];

export const flooringMaterials = [
  "Subfloor",
  "Cabinets",
  "Other",
  "Backerboard",
  "Tackless Strip",
  "Engineered Hardwood",
  "Sheet Vinyl",
  "Glued Down Carpet",
  "Gym Sports Hardwood",
  "Asbestos Tile",
  "Parquet Flooring",
  "Beurber Carpet",
  "Peel And Stick Vinyl",
  "Wood Laminate",
  "Carpet Tile",
  "Bamboo Hardwood",
  "Carpet Pad",
  "Vinyl Plank",
  "Concrete",
  "Solid Hardwood",
  "Ceramic Tile",
  "Indoor Carpet",
  "Carpet Pad",
  "Vinyl Plank",
  "Concrete",
  "Solid Hardwood",
];
